# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TourneyTime' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TourneyTime
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  target 'TourneyTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TourneyTime-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TourneyTime-tvOS

  target 'TourneyTime-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
